// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/model/proto/search_cluster_protos.proto

// Protobuf Java Version: 3.25.2
package model.proto;

public final class SearchModel {
  private SearchModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:distributed.search.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string search_query = 1;</code>
     * @return Whether the searchQuery field is set.
     */
    boolean hasSearchQuery();
    /**
     * <code>required string search_query = 1;</code>
     * @return The searchQuery.
     */
    java.lang.String getSearchQuery();
    /**
     * <code>required string search_query = 1;</code>
     * @return The bytes for searchQuery.
     */
    com.google.protobuf.ByteString
        getSearchQueryBytes();
  }
  /**
   * Protobuf type {@code distributed.search.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:distributed.search.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      searchQuery_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.proto.SearchModel.internal_static_distributed_search_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.proto.SearchModel.internal_static_distributed_search_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.proto.SearchModel.Request.class, model.proto.SearchModel.Request.Builder.class);
    }

    private int bitField0_;
    public static final int SEARCH_QUERY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object searchQuery_ = "";
    /**
     * <code>required string search_query = 1;</code>
     * @return Whether the searchQuery field is set.
     */
    @java.lang.Override
    public boolean hasSearchQuery() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string search_query = 1;</code>
     * @return The searchQuery.
     */
    @java.lang.Override
    public java.lang.String getSearchQuery() {
      java.lang.Object ref = searchQuery_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          searchQuery_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string search_query = 1;</code>
     * @return The bytes for searchQuery.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSearchQueryBytes() {
      java.lang.Object ref = searchQuery_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchQuery_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSearchQuery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, searchQuery_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, searchQuery_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.proto.SearchModel.Request)) {
        return super.equals(obj);
      }
      model.proto.SearchModel.Request other = (model.proto.SearchModel.Request) obj;

      if (hasSearchQuery() != other.hasSearchQuery()) return false;
      if (hasSearchQuery()) {
        if (!getSearchQuery()
            .equals(other.getSearchQuery())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSearchQuery()) {
        hash = (37 * hash) + SEARCH_QUERY_FIELD_NUMBER;
        hash = (53 * hash) + getSearchQuery().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.proto.SearchModel.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.SearchModel.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.SearchModel.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.SearchModel.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.SearchModel.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.SearchModel.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.SearchModel.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.proto.SearchModel.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static model.proto.SearchModel.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static model.proto.SearchModel.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.proto.SearchModel.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.proto.SearchModel.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.proto.SearchModel.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code distributed.search.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:distributed.search.Request)
        model.proto.SearchModel.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.proto.SearchModel.internal_static_distributed_search_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.proto.SearchModel.internal_static_distributed_search_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.proto.SearchModel.Request.class, model.proto.SearchModel.Request.Builder.class);
      }

      // Construct using model.proto.SearchModel.Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        searchQuery_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.proto.SearchModel.internal_static_distributed_search_Request_descriptor;
      }

      @java.lang.Override
      public model.proto.SearchModel.Request getDefaultInstanceForType() {
        return model.proto.SearchModel.Request.getDefaultInstance();
      }

      @java.lang.Override
      public model.proto.SearchModel.Request build() {
        model.proto.SearchModel.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public model.proto.SearchModel.Request buildPartial() {
        model.proto.SearchModel.Request result = new model.proto.SearchModel.Request(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(model.proto.SearchModel.Request result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.searchQuery_ = searchQuery_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.proto.SearchModel.Request) {
          return mergeFrom((model.proto.SearchModel.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.proto.SearchModel.Request other) {
        if (other == model.proto.SearchModel.Request.getDefaultInstance()) return this;
        if (other.hasSearchQuery()) {
          searchQuery_ = other.searchQuery_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSearchQuery()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                searchQuery_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object searchQuery_ = "";
      /**
       * <code>required string search_query = 1;</code>
       * @return Whether the searchQuery field is set.
       */
      public boolean hasSearchQuery() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string search_query = 1;</code>
       * @return The searchQuery.
       */
      public java.lang.String getSearchQuery() {
        java.lang.Object ref = searchQuery_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            searchQuery_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string search_query = 1;</code>
       * @return The bytes for searchQuery.
       */
      public com.google.protobuf.ByteString
          getSearchQueryBytes() {
        java.lang.Object ref = searchQuery_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          searchQuery_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string search_query = 1;</code>
       * @param value The searchQuery to set.
       * @return This builder for chaining.
       */
      public Builder setSearchQuery(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        searchQuery_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string search_query = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSearchQuery() {
        searchQuery_ = getDefaultInstance().getSearchQuery();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string search_query = 1;</code>
       * @param value The bytes for searchQuery to set.
       * @return This builder for chaining.
       */
      public Builder setSearchQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        searchQuery_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:distributed.search.Request)
    }

    // @@protoc_insertion_point(class_scope:distributed.search.Request)
    private static final model.proto.SearchModel.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.proto.SearchModel.Request();
    }

    public static model.proto.SearchModel.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public model.proto.SearchModel.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:distributed.search.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    java.util.List<model.proto.SearchModel.Response.DocumentStats> 
        getDocumentReleventList();
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    model.proto.SearchModel.Response.DocumentStats getDocumentRelevent(int index);
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    int getDocumentReleventCount();
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    java.util.List<? extends model.proto.SearchModel.Response.DocumentStatsOrBuilder> 
        getDocumentReleventOrBuilderList();
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    model.proto.SearchModel.Response.DocumentStatsOrBuilder getDocumentReleventOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code distributed.search.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:distributed.search.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      documentRelevent_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return model.proto.SearchModel.internal_static_distributed_search_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return model.proto.SearchModel.internal_static_distributed_search_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              model.proto.SearchModel.Response.class, model.proto.SearchModel.Response.Builder.class);
    }

    public interface DocumentStatsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:distributed.search.Response.DocumentStats)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string document_name = 1;</code>
       * @return Whether the documentName field is set.
       */
      boolean hasDocumentName();
      /**
       * <code>required string document_name = 1;</code>
       * @return The documentName.
       */
      java.lang.String getDocumentName();
      /**
       * <code>required string document_name = 1;</code>
       * @return The bytes for documentName.
       */
      com.google.protobuf.ByteString
          getDocumentNameBytes();

      /**
       * <code>optional double score = 2;</code>
       * @return Whether the score field is set.
       */
      boolean hasScore();
      /**
       * <code>optional double score = 2;</code>
       * @return The score.
       */
      double getScore();

      /**
       * <code>optional int64 document_size = 3;</code>
       * @return Whether the documentSize field is set.
       */
      boolean hasDocumentSize();
      /**
       * <code>optional int64 document_size = 3;</code>
       * @return The documentSize.
       */
      long getDocumentSize();

      /**
       * <code>optional string author = 4;</code>
       * @return Whether the author field is set.
       */
      boolean hasAuthor();
      /**
       * <code>optional string author = 4;</code>
       * @return The author.
       */
      java.lang.String getAuthor();
      /**
       * <code>optional string author = 4;</code>
       * @return The bytes for author.
       */
      com.google.protobuf.ByteString
          getAuthorBytes();
    }
    /**
     * Protobuf type {@code distributed.search.Response.DocumentStats}
     */
    public static final class DocumentStats extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:distributed.search.Response.DocumentStats)
        DocumentStatsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DocumentStats.newBuilder() to construct.
      private DocumentStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DocumentStats() {
        documentName_ = "";
        author_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new DocumentStats();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.proto.SearchModel.internal_static_distributed_search_Response_DocumentStats_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.proto.SearchModel.internal_static_distributed_search_Response_DocumentStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.proto.SearchModel.Response.DocumentStats.class, model.proto.SearchModel.Response.DocumentStats.Builder.class);
      }

      private int bitField0_;
      public static final int DOCUMENT_NAME_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object documentName_ = "";
      /**
       * <code>required string document_name = 1;</code>
       * @return Whether the documentName field is set.
       */
      @java.lang.Override
      public boolean hasDocumentName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string document_name = 1;</code>
       * @return The documentName.
       */
      @java.lang.Override
      public java.lang.String getDocumentName() {
        java.lang.Object ref = documentName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            documentName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string document_name = 1;</code>
       * @return The bytes for documentName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDocumentNameBytes() {
        java.lang.Object ref = documentName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          documentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SCORE_FIELD_NUMBER = 2;
      private double score_ = 0D;
      /**
       * <code>optional double score = 2;</code>
       * @return Whether the score field is set.
       */
      @java.lang.Override
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional double score = 2;</code>
       * @return The score.
       */
      @java.lang.Override
      public double getScore() {
        return score_;
      }

      public static final int DOCUMENT_SIZE_FIELD_NUMBER = 3;
      private long documentSize_ = 0L;
      /**
       * <code>optional int64 document_size = 3;</code>
       * @return Whether the documentSize field is set.
       */
      @java.lang.Override
      public boolean hasDocumentSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 document_size = 3;</code>
       * @return The documentSize.
       */
      @java.lang.Override
      public long getDocumentSize() {
        return documentSize_;
      }

      public static final int AUTHOR_FIELD_NUMBER = 4;
      @SuppressWarnings("serial")
      private volatile java.lang.Object author_ = "";
      /**
       * <code>optional string author = 4;</code>
       * @return Whether the author field is set.
       */
      @java.lang.Override
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string author = 4;</code>
       * @return The author.
       */
      @java.lang.Override
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            author_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string author = 4;</code>
       * @return The bytes for author.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDocumentName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, documentName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeDouble(2, score_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeInt64(3, documentSize_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, author_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, documentName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, score_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, documentSize_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, author_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof model.proto.SearchModel.Response.DocumentStats)) {
          return super.equals(obj);
        }
        model.proto.SearchModel.Response.DocumentStats other = (model.proto.SearchModel.Response.DocumentStats) obj;

        if (hasDocumentName() != other.hasDocumentName()) return false;
        if (hasDocumentName()) {
          if (!getDocumentName()
              .equals(other.getDocumentName())) return false;
        }
        if (hasScore() != other.hasScore()) return false;
        if (hasScore()) {
          if (java.lang.Double.doubleToLongBits(getScore())
              != java.lang.Double.doubleToLongBits(
                  other.getScore())) return false;
        }
        if (hasDocumentSize() != other.hasDocumentSize()) return false;
        if (hasDocumentSize()) {
          if (getDocumentSize()
              != other.getDocumentSize()) return false;
        }
        if (hasAuthor() != other.hasAuthor()) return false;
        if (hasAuthor()) {
          if (!getAuthor()
              .equals(other.getAuthor())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasDocumentName()) {
          hash = (37 * hash) + DOCUMENT_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getDocumentName().hashCode();
        }
        if (hasScore()) {
          hash = (37 * hash) + SCORE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getScore()));
        }
        if (hasDocumentSize()) {
          hash = (37 * hash) + DOCUMENT_SIZE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getDocumentSize());
        }
        if (hasAuthor()) {
          hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
          hash = (53 * hash) + getAuthor().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static model.proto.SearchModel.Response.DocumentStats parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static model.proto.SearchModel.Response.DocumentStats parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static model.proto.SearchModel.Response.DocumentStats parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static model.proto.SearchModel.Response.DocumentStats parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(model.proto.SearchModel.Response.DocumentStats prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code distributed.search.Response.DocumentStats}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:distributed.search.Response.DocumentStats)
          model.proto.SearchModel.Response.DocumentStatsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return model.proto.SearchModel.internal_static_distributed_search_Response_DocumentStats_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return model.proto.SearchModel.internal_static_distributed_search_Response_DocumentStats_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  model.proto.SearchModel.Response.DocumentStats.class, model.proto.SearchModel.Response.DocumentStats.Builder.class);
        }

        // Construct using model.proto.SearchModel.Response.DocumentStats.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          documentName_ = "";
          score_ = 0D;
          documentSize_ = 0L;
          author_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return model.proto.SearchModel.internal_static_distributed_search_Response_DocumentStats_descriptor;
        }

        @java.lang.Override
        public model.proto.SearchModel.Response.DocumentStats getDefaultInstanceForType() {
          return model.proto.SearchModel.Response.DocumentStats.getDefaultInstance();
        }

        @java.lang.Override
        public model.proto.SearchModel.Response.DocumentStats build() {
          model.proto.SearchModel.Response.DocumentStats result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public model.proto.SearchModel.Response.DocumentStats buildPartial() {
          model.proto.SearchModel.Response.DocumentStats result = new model.proto.SearchModel.Response.DocumentStats(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(model.proto.SearchModel.Response.DocumentStats result) {
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.documentName_ = documentName_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.score_ = score_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.documentSize_ = documentSize_;
            to_bitField0_ |= 0x00000004;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.author_ = author_;
            to_bitField0_ |= 0x00000008;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof model.proto.SearchModel.Response.DocumentStats) {
            return mergeFrom((model.proto.SearchModel.Response.DocumentStats)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(model.proto.SearchModel.Response.DocumentStats other) {
          if (other == model.proto.SearchModel.Response.DocumentStats.getDefaultInstance()) return this;
          if (other.hasDocumentName()) {
            documentName_ = other.documentName_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.hasScore()) {
            setScore(other.getScore());
          }
          if (other.hasDocumentSize()) {
            setDocumentSize(other.getDocumentSize());
          }
          if (other.hasAuthor()) {
            author_ = other.author_;
            bitField0_ |= 0x00000008;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasDocumentName()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  documentName_ = input.readBytes();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 17: {
                  score_ = input.readDouble();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 17
                case 24: {
                  documentSize_ = input.readInt64();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                case 34: {
                  author_ = input.readBytes();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 34
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object documentName_ = "";
        /**
         * <code>required string document_name = 1;</code>
         * @return Whether the documentName field is set.
         */
        public boolean hasDocumentName() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string document_name = 1;</code>
         * @return The documentName.
         */
        public java.lang.String getDocumentName() {
          java.lang.Object ref = documentName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              documentName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string document_name = 1;</code>
         * @return The bytes for documentName.
         */
        public com.google.protobuf.ByteString
            getDocumentNameBytes() {
          java.lang.Object ref = documentName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            documentName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string document_name = 1;</code>
         * @param value The documentName to set.
         * @return This builder for chaining.
         */
        public Builder setDocumentName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          documentName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>required string document_name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearDocumentName() {
          documentName_ = getDefaultInstance().getDocumentName();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>required string document_name = 1;</code>
         * @param value The bytes for documentName to set.
         * @return This builder for chaining.
         */
        public Builder setDocumentNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          documentName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private double score_ ;
        /**
         * <code>optional double score = 2;</code>
         * @return Whether the score field is set.
         */
        @java.lang.Override
        public boolean hasScore() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional double score = 2;</code>
         * @return The score.
         */
        @java.lang.Override
        public double getScore() {
          return score_;
        }
        /**
         * <code>optional double score = 2;</code>
         * @param value The score to set.
         * @return This builder for chaining.
         */
        public Builder setScore(double value) {

          score_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>optional double score = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearScore() {
          bitField0_ = (bitField0_ & ~0x00000002);
          score_ = 0D;
          onChanged();
          return this;
        }

        private long documentSize_ ;
        /**
         * <code>optional int64 document_size = 3;</code>
         * @return Whether the documentSize field is set.
         */
        @java.lang.Override
        public boolean hasDocumentSize() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional int64 document_size = 3;</code>
         * @return The documentSize.
         */
        @java.lang.Override
        public long getDocumentSize() {
          return documentSize_;
        }
        /**
         * <code>optional int64 document_size = 3;</code>
         * @param value The documentSize to set.
         * @return This builder for chaining.
         */
        public Builder setDocumentSize(long value) {

          documentSize_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 document_size = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearDocumentSize() {
          bitField0_ = (bitField0_ & ~0x00000004);
          documentSize_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object author_ = "";
        /**
         * <code>optional string author = 4;</code>
         * @return Whether the author field is set.
         */
        public boolean hasAuthor() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional string author = 4;</code>
         * @return The author.
         */
        public java.lang.String getAuthor() {
          java.lang.Object ref = author_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              author_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string author = 4;</code>
         * @return The bytes for author.
         */
        public com.google.protobuf.ByteString
            getAuthorBytes() {
          java.lang.Object ref = author_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            author_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string author = 4;</code>
         * @param value The author to set.
         * @return This builder for chaining.
         */
        public Builder setAuthor(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          author_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>optional string author = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearAuthor() {
          author_ = getDefaultInstance().getAuthor();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        /**
         * <code>optional string author = 4;</code>
         * @param value The bytes for author to set.
         * @return This builder for chaining.
         */
        public Builder setAuthorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          author_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:distributed.search.Response.DocumentStats)
      }

      // @@protoc_insertion_point(class_scope:distributed.search.Response.DocumentStats)
      private static final model.proto.SearchModel.Response.DocumentStats DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new model.proto.SearchModel.Response.DocumentStats();
      }

      public static model.proto.SearchModel.Response.DocumentStats getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<DocumentStats>
          PARSER = new com.google.protobuf.AbstractParser<DocumentStats>() {
        @java.lang.Override
        public DocumentStats parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<DocumentStats> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DocumentStats> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public model.proto.SearchModel.Response.DocumentStats getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DOCUMENT_RELEVENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<model.proto.SearchModel.Response.DocumentStats> documentRelevent_;
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    @java.lang.Override
    public java.util.List<model.proto.SearchModel.Response.DocumentStats> getDocumentReleventList() {
      return documentRelevent_;
    }
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends model.proto.SearchModel.Response.DocumentStatsOrBuilder> 
        getDocumentReleventOrBuilderList() {
      return documentRelevent_;
    }
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    @java.lang.Override
    public int getDocumentReleventCount() {
      return documentRelevent_.size();
    }
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    @java.lang.Override
    public model.proto.SearchModel.Response.DocumentStats getDocumentRelevent(int index) {
      return documentRelevent_.get(index);
    }
    /**
     * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
     */
    @java.lang.Override
    public model.proto.SearchModel.Response.DocumentStatsOrBuilder getDocumentReleventOrBuilder(
        int index) {
      return documentRelevent_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDocumentReleventCount(); i++) {
        if (!getDocumentRelevent(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < documentRelevent_.size(); i++) {
        output.writeMessage(1, documentRelevent_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < documentRelevent_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, documentRelevent_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof model.proto.SearchModel.Response)) {
        return super.equals(obj);
      }
      model.proto.SearchModel.Response other = (model.proto.SearchModel.Response) obj;

      if (!getDocumentReleventList()
          .equals(other.getDocumentReleventList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDocumentReleventCount() > 0) {
        hash = (37 * hash) + DOCUMENT_RELEVENT_FIELD_NUMBER;
        hash = (53 * hash) + getDocumentReleventList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static model.proto.SearchModel.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.SearchModel.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.SearchModel.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.SearchModel.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.SearchModel.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static model.proto.SearchModel.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static model.proto.SearchModel.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.proto.SearchModel.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static model.proto.SearchModel.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static model.proto.SearchModel.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static model.proto.SearchModel.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static model.proto.SearchModel.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(model.proto.SearchModel.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code distributed.search.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:distributed.search.Response)
        model.proto.SearchModel.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return model.proto.SearchModel.internal_static_distributed_search_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return model.proto.SearchModel.internal_static_distributed_search_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                model.proto.SearchModel.Response.class, model.proto.SearchModel.Response.Builder.class);
      }

      // Construct using model.proto.SearchModel.Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (documentReleventBuilder_ == null) {
          documentRelevent_ = java.util.Collections.emptyList();
        } else {
          documentRelevent_ = null;
          documentReleventBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return model.proto.SearchModel.internal_static_distributed_search_Response_descriptor;
      }

      @java.lang.Override
      public model.proto.SearchModel.Response getDefaultInstanceForType() {
        return model.proto.SearchModel.Response.getDefaultInstance();
      }

      @java.lang.Override
      public model.proto.SearchModel.Response build() {
        model.proto.SearchModel.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public model.proto.SearchModel.Response buildPartial() {
        model.proto.SearchModel.Response result = new model.proto.SearchModel.Response(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(model.proto.SearchModel.Response result) {
        if (documentReleventBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            documentRelevent_ = java.util.Collections.unmodifiableList(documentRelevent_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.documentRelevent_ = documentRelevent_;
        } else {
          result.documentRelevent_ = documentReleventBuilder_.build();
        }
      }

      private void buildPartial0(model.proto.SearchModel.Response result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof model.proto.SearchModel.Response) {
          return mergeFrom((model.proto.SearchModel.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(model.proto.SearchModel.Response other) {
        if (other == model.proto.SearchModel.Response.getDefaultInstance()) return this;
        if (documentReleventBuilder_ == null) {
          if (!other.documentRelevent_.isEmpty()) {
            if (documentRelevent_.isEmpty()) {
              documentRelevent_ = other.documentRelevent_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDocumentReleventIsMutable();
              documentRelevent_.addAll(other.documentRelevent_);
            }
            onChanged();
          }
        } else {
          if (!other.documentRelevent_.isEmpty()) {
            if (documentReleventBuilder_.isEmpty()) {
              documentReleventBuilder_.dispose();
              documentReleventBuilder_ = null;
              documentRelevent_ = other.documentRelevent_;
              bitField0_ = (bitField0_ & ~0x00000001);
              documentReleventBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDocumentReleventFieldBuilder() : null;
            } else {
              documentReleventBuilder_.addAllMessages(other.documentRelevent_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getDocumentReleventCount(); i++) {
          if (!getDocumentRelevent(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                model.proto.SearchModel.Response.DocumentStats m =
                    input.readMessage(
                        model.proto.SearchModel.Response.DocumentStats.PARSER,
                        extensionRegistry);
                if (documentReleventBuilder_ == null) {
                  ensureDocumentReleventIsMutable();
                  documentRelevent_.add(m);
                } else {
                  documentReleventBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<model.proto.SearchModel.Response.DocumentStats> documentRelevent_ =
        java.util.Collections.emptyList();
      private void ensureDocumentReleventIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          documentRelevent_ = new java.util.ArrayList<model.proto.SearchModel.Response.DocumentStats>(documentRelevent_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          model.proto.SearchModel.Response.DocumentStats, model.proto.SearchModel.Response.DocumentStats.Builder, model.proto.SearchModel.Response.DocumentStatsOrBuilder> documentReleventBuilder_;

      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public java.util.List<model.proto.SearchModel.Response.DocumentStats> getDocumentReleventList() {
        if (documentReleventBuilder_ == null) {
          return java.util.Collections.unmodifiableList(documentRelevent_);
        } else {
          return documentReleventBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public int getDocumentReleventCount() {
        if (documentReleventBuilder_ == null) {
          return documentRelevent_.size();
        } else {
          return documentReleventBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public model.proto.SearchModel.Response.DocumentStats getDocumentRelevent(int index) {
        if (documentReleventBuilder_ == null) {
          return documentRelevent_.get(index);
        } else {
          return documentReleventBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder setDocumentRelevent(
          int index, model.proto.SearchModel.Response.DocumentStats value) {
        if (documentReleventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentReleventIsMutable();
          documentRelevent_.set(index, value);
          onChanged();
        } else {
          documentReleventBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder setDocumentRelevent(
          int index, model.proto.SearchModel.Response.DocumentStats.Builder builderForValue) {
        if (documentReleventBuilder_ == null) {
          ensureDocumentReleventIsMutable();
          documentRelevent_.set(index, builderForValue.build());
          onChanged();
        } else {
          documentReleventBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder addDocumentRelevent(model.proto.SearchModel.Response.DocumentStats value) {
        if (documentReleventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentReleventIsMutable();
          documentRelevent_.add(value);
          onChanged();
        } else {
          documentReleventBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder addDocumentRelevent(
          int index, model.proto.SearchModel.Response.DocumentStats value) {
        if (documentReleventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentReleventIsMutable();
          documentRelevent_.add(index, value);
          onChanged();
        } else {
          documentReleventBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder addDocumentRelevent(
          model.proto.SearchModel.Response.DocumentStats.Builder builderForValue) {
        if (documentReleventBuilder_ == null) {
          ensureDocumentReleventIsMutable();
          documentRelevent_.add(builderForValue.build());
          onChanged();
        } else {
          documentReleventBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder addDocumentRelevent(
          int index, model.proto.SearchModel.Response.DocumentStats.Builder builderForValue) {
        if (documentReleventBuilder_ == null) {
          ensureDocumentReleventIsMutable();
          documentRelevent_.add(index, builderForValue.build());
          onChanged();
        } else {
          documentReleventBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder addAllDocumentRelevent(
          java.lang.Iterable<? extends model.proto.SearchModel.Response.DocumentStats> values) {
        if (documentReleventBuilder_ == null) {
          ensureDocumentReleventIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, documentRelevent_);
          onChanged();
        } else {
          documentReleventBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder clearDocumentRelevent() {
        if (documentReleventBuilder_ == null) {
          documentRelevent_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          documentReleventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public Builder removeDocumentRelevent(int index) {
        if (documentReleventBuilder_ == null) {
          ensureDocumentReleventIsMutable();
          documentRelevent_.remove(index);
          onChanged();
        } else {
          documentReleventBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public model.proto.SearchModel.Response.DocumentStats.Builder getDocumentReleventBuilder(
          int index) {
        return getDocumentReleventFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public model.proto.SearchModel.Response.DocumentStatsOrBuilder getDocumentReleventOrBuilder(
          int index) {
        if (documentReleventBuilder_ == null) {
          return documentRelevent_.get(index);  } else {
          return documentReleventBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public java.util.List<? extends model.proto.SearchModel.Response.DocumentStatsOrBuilder> 
           getDocumentReleventOrBuilderList() {
        if (documentReleventBuilder_ != null) {
          return documentReleventBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(documentRelevent_);
        }
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public model.proto.SearchModel.Response.DocumentStats.Builder addDocumentReleventBuilder() {
        return getDocumentReleventFieldBuilder().addBuilder(
            model.proto.SearchModel.Response.DocumentStats.getDefaultInstance());
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public model.proto.SearchModel.Response.DocumentStats.Builder addDocumentReleventBuilder(
          int index) {
        return getDocumentReleventFieldBuilder().addBuilder(
            index, model.proto.SearchModel.Response.DocumentStats.getDefaultInstance());
      }
      /**
       * <code>repeated .distributed.search.Response.DocumentStats document_relevent = 1;</code>
       */
      public java.util.List<model.proto.SearchModel.Response.DocumentStats.Builder> 
           getDocumentReleventBuilderList() {
        return getDocumentReleventFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          model.proto.SearchModel.Response.DocumentStats, model.proto.SearchModel.Response.DocumentStats.Builder, model.proto.SearchModel.Response.DocumentStatsOrBuilder> 
          getDocumentReleventFieldBuilder() {
        if (documentReleventBuilder_ == null) {
          documentReleventBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              model.proto.SearchModel.Response.DocumentStats, model.proto.SearchModel.Response.DocumentStats.Builder, model.proto.SearchModel.Response.DocumentStatsOrBuilder>(
                  documentRelevent_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          documentRelevent_ = null;
        }
        return documentReleventBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:distributed.search.Response)
    }

    // @@protoc_insertion_point(class_scope:distributed.search.Response)
    private static final model.proto.SearchModel.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new model.proto.SearchModel.Response();
    }

    public static model.proto.SearchModel.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public model.proto.SearchModel.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_Response_DocumentStats_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_Response_DocumentStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5src/main/java/model/proto/search_clust" +
      "er_protos.proto\022\022distributed.search\"\037\n\007R" +
      "equest\022\024\n\014search_query\030\001 \002(\t\"\257\001\n\010Respons" +
      "e\022E\n\021document_relevent\030\001 \003(\0132*.distribut" +
      "ed.search.Response.DocumentStats\032\\\n\rDocu" +
      "mentStats\022\025\n\rdocument_name\030\001 \002(\t\022\r\n\005scor" +
      "e\030\002 \001(\001\022\025\n\rdocument_size\030\003 \001(\003\022\016\n\006author" +
      "\030\004 \001(\tB\032\n\013model.protoB\013SearchModel"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_distributed_search_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_distributed_search_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_Request_descriptor,
        new java.lang.String[] { "SearchQuery", });
    internal_static_distributed_search_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_distributed_search_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_Response_descriptor,
        new java.lang.String[] { "DocumentRelevent", });
    internal_static_distributed_search_Response_DocumentStats_descriptor =
      internal_static_distributed_search_Response_descriptor.getNestedTypes().get(0);
    internal_static_distributed_search_Response_DocumentStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_Response_DocumentStats_descriptor,
        new java.lang.String[] { "DocumentName", "Score", "DocumentSize", "Author", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
